# Generated by Django 4.2.11 on 2024-03-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantprice',
            options={'ordering': ('product',)},
        ),
    ]
